version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - '3308:3308'
    environment:
       MYSQL_DATABASE: 'django'
       MYSQL_USER: 'django'
       MYSQL_PASSWORD: 'django'
       MYSQL_ROOT_PASSWORD: '123qwe123'
    volumes:
      - .setup.sql:/docker-entrypoint-initdb.d/setup.sql

  web:
    container_name: web
    build: .
    command: gunicorn --bind 0.0.0.0:8000 django_project.wsgi
    volumes:
      - .:/django_project
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/home/app/web
    ports:
      - "8080:80"
    depends_on:
      - web
